/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.tagSoup.cc;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.text.Html;
import android.content.Intent;
import android.app.Activity;

@Kroll.module(name="TagSoup", id="com.tagSoup.cc")
public class TagSoupModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TagSoupModule";
	private static final boolean DBG = TiConfig.LOGD;

	public TagSoupModule( ) {
		super( );
	}

	@Kroll.onAppCreate
	public static void onAppCreate( TiApplication app ) {
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}
    
    @Kroll.method
    /*
     * Dispatches an intent with Spannable text to other apps.
     * With it is possible to transform HTML into an email ;)
     */
    public void dispatchHTML( String title, String subject, String contents  ){
        
        Intent intent = new Intent( Intent.ACTION_SEND );

        intent.setType("text/html");
        intent.putExtra( Intent.EXTRA_SUBJECT, subject);

        //TagSoup line that avoids Titanium from sharing HTML intents to GMail Android app
        intent.putExtra( Intent.EXTRA_TEXT, Html.fromHtml( contents ) );
        
        TiApplication appContext = TiApplication.getInstance();
        Activity activity = appContext.getCurrentActivity();
        
        if ( title == null ) {
            title = "Share";
        }
        
        activity.startActivity(Intent.createChooser(intent, title));
    }
}